import type { Metadata } from "next";
import { TourbitProvider } from "@tourbit/cli";
import localFont from "next/font/local";
import "./globals.css";
import { TanstackProvider } from "@/providers/tanstack-provider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanstackProvider>
          <TourbitProvider
            apiKey={process.env.NEXT_PUBLIC_TOURBIT_API_KEY as string}
            userId={"23456ff"}
            user={{
              name: "Trust",
              email: "trustonye@gmail.com",
            }}
          >
           {children}
            <Toaster richColors closeButton position="top-left" />
          </TourbitProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
