name: Publish CLI to NPM

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      # Setup Turborepo cache
      - uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      
      # Install dependencies
      - run: npm ci
      
      # Build all packages
      - run: npx turbo run build
      
      # Run tests (if applicable)
      - run: npx turbo run test
      
      # Publish CLI
      - run: npm publish -w apps/cli --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}